config/routes.rb
Rails.application.routes.draw do
  root to: "notes#index"
  devise_for :users
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates_presence_of :text
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  def index
    @notes = Note.all
    @note = Note.new
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
    unless @note.user == current_user
      respond_to do |format|
        format.html { redirect_to notes_url, notice: 'You can only edit your notes.' }
        format.json { head :no_content }
      end
    end
  end

  def create
    @note = Note.new(note_params)
    @note.user = current_user
    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_url, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_url, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    unless @note.user == current_user
      respond_to do |format|
        format.html { redirect_to notes_url, notice: 'You can only edit your notes.' }
        format.json { head :no_content }
      end
    else
      @note.destroy
      respond_to do |format|
        format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:text, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand">Notes App</a>
      <% if user_signed_in? %>
        <span class="navbar-text">
          Hello, <%= current_user.email %>
        </span>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-success my-2 my-sm-0' %>
      <% else %>
        <%= link_to "Log in", new_user_session_path, class: 'btn btn-outline-success my-2 my-sm-0' %>
      <% end %>
    </nav>
    <p id="notice"><%= notice %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Enter a new note:</h3>
  <div class="form-group">
    <%= form.text_field :text, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Add Note", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<div class="row">
  <% @notes.each do |note| %>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Note from <%= note.user.email %></h5>
          <p class="card-text"><%= note.text %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>


<%= render 'form', note: @note %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>